version: "2"

services:
  nexus:
    image: sonatype/nexus3
    container_name: sonatype-nexus
    restart: unless-stopped
    volumes:
      - "nexus-data:/nexus-data"
    ports:
      - "8081:8081"

volumes:
  nexus-data: {}