version: "3"

services:
  sonarqube:
    image: sonarqube
    container_name: sonarqube_app
    restart: unless-stopped
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_USERNAME=sonarqube
      - SONARQUBE_JDBC_PASSWORD=sonarpass
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
      - sonar.coverage.jacoco.xmlReportPaths=/tmp/jacoco/report.xml
#      - sonar.jdbc.username=sonar
#      - sonar.jdbc.password=sonar
#      - sonar.jdbc.url=jdbc:postgresql://db/sonar
    ports:
      - "9090:9000"
      - "9092:9092"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
  db:
    networks:
      - sonarnet
    image: postgres
    container_name: sonarqube_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=sonarqube
      - POSTGRES_PASSWORD=sonarpass
      - POSTGRES_DB=sonarqube
    volumes:
      - sonarqube_db:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge

volumes:
  postgresql_data:
  sonarqube_bundled-plugins:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_db:
  sonarqube_extensions: