version: '3'
services:
  app:
    image: florider89/joplin-server:2.7.4
    container_name: joplin-server-app
    restart: unless-stopped
    environment:
      - APP_BASE_URL=http://joplin.yourdomain.tld:22300
      - APP_PORT=22300
      - POSTGRES_PASSWORD=joplin
      - POSTGRES_DATABASE=joplin
      - POSTGRES_USER=joplin
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
      - DB_CLIENT=pg
    ports:
      - "22300:22300"
  db:
    image: postgres:13.1
    container_name: joplin-server-db
    restart: unless-stopped
#    ports:
#      - "5432:5432"
    volumes:
      - ~/joplin-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=joplin
      - POSTGRES_USER=joplin
      - POSTGRES_DB=joplin