version: "3.4"

services:
  gitea-rpi:
    image: kapdap/gitea-rpi
    container_name: gitea-rpi
    restart: always
    volumes:
      - "${DATA_PATH}/gitea-rpi:/data"
    ports:
      - "2221:22"
      - "3001:3000"
