version: "3"

services:
  cups:
#    image: olbat/cupsd
    image: lemariva/rpi-cups
    container_name: cups
    restart: always
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /dev/bus/usb:/dev/bus/usb
    ports:
      - "6311:631"