version: "3"

services:
  homeassistant:
    container_name: homeassistant
    image: "homeassistant/raspberrypi4-homeassistant:stable"
    restart: unless-stopped
    volumes:
      - ~/home-assistant-config:/config
      - /etc/localtime:/etc/localtime:ro
    privileged: true
#    network_mode: host
    ports:
      - "8123:8123"