version: "3"
services:
  grafana:
    container_name: monitoring-grafana
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_PATHS_HOME=/usr/share/grafana
      - GF_PATHS_LOGS=/var/log/grafana
      - GF_PATHS_PLUGINS=/var/lib/grafana/plugins
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    hostname: rpi-grafana
    image: grafana/grafana:latest
#    networks:
#      - rpimonitor_default
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      # to be modified depending on your needs
      - ~/pg-test/grafana/data:/var/lib/grafana
      - ~/pg-test/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ~/pg-test/grafana/provisioning:/etc/grafana/provisioning

  prometheus:
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    container_name: monitoring-prometheus
    ports:
      - 9099:9090
#    expose:
#      - 9090
    hostname: rpi-prom
    image: prom/prometheus:latest
#    networks:
#      - rpimonitor_default
    restart: unless-stopped
    volumes:
      # to be modified depending on your needs
      - ~/pg-test/prometheus/data:/prometheus
      - ~/pg-test/prometheus/config:/etc/prometheus/
#    links:
#      - cadvisor:cadvisor
#      - node-exporter:node-exporter

#  cadvisor:
#    container_name: monitoring-cadvisor
#    devices:
#      - /dev/kmsg
#    expose:
#      - 8080
#    hostname: rpi-cadvisor
#    image: zcube/cadvisor:latest
#    ipc: shareable
#    networks:
#      - rpimonitor_default
#    privileged: true
#    restart: unless-stopped
#    security_opt:
#      - label=disable
#    volumes:
#      - /:/rootfs:ro
#      - /var/run:/var/run:ro
#      - /sys:/sys:ro
#      - /var/lib/docker/:/var/lib/docker:ro
#      - /dev/disk/:/dev/disk:ro

#  node-exporter:
#    container_name: monitoring-node-exporter
#    expose:
#      - 9100
#    hostname: rpi-exporter
#    image: prom/node-exporter:latest
#    networks:
#      - rpimonitor_default
#    restart: unless-stopped

#networks:
#  rpimonitor_default:
#    external: true

# https://github.com/oijkn/Docker-Raspberry-PI-Monitoring