scrape_configs:
  - job_name: 'rpi'
    scrape_interval: 10s
    static_configs:
#      - targets: ['localhost:9090', 'cadvisor:8080', 'node-exporter:9100']
      - targets: ['192.168.192.180:8080', '192.168.192.180:9100']

  - job_name: 'prometheus_local'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
