version: "3"

volumes:
  mongodata:

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    restart: unless-stopped
    volumes:
      - mongodata:/data/db
#      - "C:\dockerdata\mongodata:/data/db"
    ports:
      - "27017:27017"