#scrape_configs:
#  - job_name: 'prometheus'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['localhost:9090', 'cadvisor:8080', 'node-exporter:9100']

global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.

# Write to VictoriaMetrics
#remote_write:
#  - url: http://victoria-metrics:8428/api/v1/write

scrape_configs:
  - job_name: 'pi_cpu_stats'
    static_configs:
      - targets: ['rpi_cpu_stats:9669']

#  - job_name: 'vmagent'
#    static_configs:
#      - targets: ['vmagent:8429']

  - job_name: 'victoria_metrics_stats'
    static_configs:
      - targets: ['victoria-metrics:8428']

  - job_name: 'blackbox_ping'
    metrics_path: /probe
    scrape_interval: 30s
    params:
      module: [icmp]
    static_configs:
      - targets:
          - 8.8.8.8
          - 1.1.1.1
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115  # The blackbox exporter's real hostname:port.