version: "3"

#volumes:
#  ncdata:

services:
  nextcloud:
    image: ownyourbits/nextcloudpi
    container_name: nextcloudpi
    restart: unless-stopped
    volumes:
#      - ncdata:/data
      - type: bind
        source: /mnt/usb1/docker/volumes/ncdata
        target: /data
    ports:
      - "4443:4443"
      - "443:443"
      - "80:80"