version: "3.7"

networks:
  gitea:
    external: false

volumes:
  gitea:
    driver: local
  gitea-db:

services:
  server:
#    image: gitea/gitea:1.14.1
#    image: kapdap/gitea-rpi
#    image: strobi/rpi-gitea:latest
    image: kunde21/gitea-arm:latest
    container_name: gitea-rpi
    environment:
#      - USER_UID=1000
#      - USER_GID=1000
      - GITEA__database__TYPE=postgres
##      - GITEA__database__HOST=db:3306
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
#      - DB_TYPE=postgres
#      - DB_HOST=db:5432
#      - DB_NAME=gitea
#      - DB_USER=gitea
#      - DB_PASSWD=gitea
    restart: always
    networks:
      - gitea
    volumes:
      - gitea:/data
#      - ./gitea:/data
#      - ${DRIVE}${DIR1}:/data

#      - type: bind
##        source: C:\dockerdata\gitea
#        source: ${DATA_PATH}/gitea-mysql${GITEA_DIR}
#        target: /data
#      - /etc/timezone:/etc/timezone:ro
#      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
     - db
  db:
#    image: mysql:5.7
#    image: bjartscular/low-memory-mysql:1.0
    image: postgres:alpine
    container_name: gitea-db
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
#      - MYSQL_ROOT_PASSWORD=gitea
#      - MYSQL_USER=gitea
#      - MYSQL_PASSWORD=gitea
#      - MYSQL_DATABASE=gitea
    networks:
      - gitea
    volumes:
      - gitea-db:/var/lib/postgresql
#      - ./mysql:/var/lib/mysql
#      - ${DRIVE}${DIR2}:/data:/var/lib/mysql
#      - /dockerdata:/data:/var/lib/mysql


#      - type: bind
##        source: C:\dockerdata\gitea-db
#        source: ${DATA_PATH}/gitea-mysql${GITEA_DB}
#        target: /var/lib/postgresql
##        target: /var/lib/mysql