version: "3"

networks:
  gitea:
    external: false

volumes:
  gitea:
    driver: local

services:
  server:
    image: gitea/gitea:1.14.1
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: always
    networks:
      - gitea
    volumes:
#      - ./gitea:/data
#      - ${DRIVE}${DIR1}:/data
      - type: bind
#        source: C:\dockerdata\gitea
        source: ${DRIVE}${DIR1}
        target: /data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
     - db
  db:
#    image: mysql:5.7
    image: bjartscular/low-memory-mysql:1.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    networks:
      - gitea
    volumes:
#      - ./mysql:/var/lib/mysql
#      - ${DRIVE}${DIR2}:/data:/var/lib/mysql
#      - /dockerdata:/data:/var/lib/mysql
      - type: bind
#        source: C:\dockerdata\gitea-db
        source: ${DRIVE}${DIR2}
        target: /var/lib/mysql