version: "3.4"

services:
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: unless-stopped
    ports:
      - 127.0.0.1:8086:8086
      # - 8083:8083 # ADMINISTRATOR PORT
    volumes:
      - "./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro"
      - "influxdb:/var/lib/influxdb"
#      - "${DATA_PATH}/influxdb:/var/lib/influxdb"
    environment:
      INFLUXDB_DB: telegraf_metrics
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
#      INFLUXDB_USER: telegraf
#      INFLUXDB_USER_PASSWORD: telegraf
      INFLUXDB_WRITE_USER: telegraf
      INFLUXDB_WRITE_USER_PASSWORD: telegraf
#    entrypoint:
#      - "/entrypoint.sh"
#      - "-config"
#      - "/etc/influxdb/influxdb.conf"
#    depends_on:
#      - influxdb-init
    networks:
      - tig-monitoring

  telegraf:
    image: telegraf
    container_name: telegraf
    restart: unless-stopped
#    network_mode: "service:influxdb"
    volumes:
#      - "/:/hostfs:ro"
      - "./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro"
#      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/root/services/cpugpu/data:/host/temperature"
      - "/proc:/rootfs/proc:ro"
      - "/sys:/rootfs/sys:ro"
      - "/etc:/rootfs/etc:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      HOST_PROC: /hostfs/proc
      HOST_MOUNT_PREFIX: /hostfs
    networks:
      - tig-monitoring

networks:
  tig-monitoring:

volumes:
  influxdb: