version: "2"

services:
  nexus:
    image: klo2k/nexus3
    container_name: sonatype-nexus
    restart: unless-stopped
    volumes:
      - "nexus-data:/nexus-data"
    ports:
      - "8081:8081"
      - "2000-2020:2000-2020"

volumes:
  nexus-data: {}