---
version: "2.1"
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:arm64v8-1.20.2
    container_name: syncthing
    restart: unless-stopped
    hostname: syncthing #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
    volumes:
      - /mnt/usb1/syncthing/config:/config
      - /mnt/usb1/syncthing/data:/data
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp